ALTER TABLE t_p5255237_telegram_bot_service.users
ADD COLUMN IF NOT EXISTS full_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
ADD COLUMN IF NOT EXISTS email VARCHAR(255),
ADD COLUMN IF NOT EXISTS entity_type VARCHAR(20) DEFAULT 'individual',
ADD COLUMN IF NOT EXISTS legal_details TEXT,
ADD COLUMN IF NOT EXISTS agreed_to_terms BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS agreed_to_cookies BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS registration_completed BOOLEAN DEFAULT false;
